### ISSUE TITLE
typo in src/chumak_router.erl?

### ISSUE THREAD

**Issue by neildunbar** [chovencorp/chumak#2]
Hi there,

I think that line 97 in src/chumak_router.erl:

>         NewLBs = chumak_lb:delete(LBs, PeerPid),

is supposed to be

>         NewLBs = chumak_lbs:delete(LBs, PeerPid),

With the existing version, a client dropping its connection to the router causes a `:lists.delete` exception, but with the modified version, it works just fine.

Cheers,

Neil

**Comment by drozzy** [comment]
Thanks!
